### Get garages
GET https://api-custodia.custodia-workspace.dev/garage
Content-Type: application/json

### Get vehicles
GET https://api-custodia.custodia-workspace.dev/vehicle
Content-Type: application/json

### Get vehicle categories
GET https://api-custodia.custodia-workspace.dev/vehicle-category
Content-Type: application/json

### Get vehicle brands
GET https://api-custodia.custodia-workspace.dev/vehicle-brand
Content-Type: application/json

### Get vehicle brands
GET https://api-custodia.custodia-workspace.dev/vehicle-model
Content-Type: application/json

### Get vehicle states
GET https://api-custodia.custodia-workspace.dev/vehicle-state
Content-Type: application/json

### Get fuel types
GET https://api-custodia.custodia-workspace.dev/fuel-type
Content-Type: application/json

### Get intervention types
GET https://api-custodia.custodia-workspace.dev/intervention-category
Content-Type: application/json
